[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_staking = "1gGFthN24CB1p2LEvmhpnJVHAHm3koZDQnHgDoe6Ra2"

[programs.devnet]
solana_staking = "1gGFthN24CB1p2LEvmhpnJVHAHm3koZDQnHgDoe6Ra2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

[test]
startup_wait = 10000
